# Generated by Django 5.1 on 2025-04-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('data_type', models.CharField(max_length=50)),
                ('json_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
