# Generated by Django 2.2.2 on 2021-09-25 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktodo',
            name='task_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
